// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class DropBirdDropPlayService
{
        public const string achievement_pro_reviver = "CgkI8b-_5ZsaEAIQEQ"; // <GPGSID>
        public const string achievement_ultimate_bird = "CgkI8b-_5ZsaEAIQAw"; // <GPGSID>
        public const string achievement_ultimate_collecter = "CgkI8b-_5ZsaEAIQCA"; // <GPGSID>
        public const string achievement_all_birds = "CgkI8b-_5ZsaEAIQFQ"; // <GPGSID>
        public const string achievement_all_star_bird = "CgkI8b-_5ZsaEAIQBA"; // <GPGSID>
        public const string achievement_pro_collecter = "CgkI8b-_5ZsaEAIQBw"; // <GPGSID>
        public const string achievement_ultimate_dropper = "CgkI8b-_5ZsaEAIQDQ"; // <GPGSID>
        public const string achievement_5_birds = "CgkI8b-_5ZsaEAIQFA"; // <GPGSID>
        public const string achievement_pro_dropper = "CgkI8b-_5ZsaEAIQDA"; // <GPGSID>
        public const string achievement_rookie_bird = "CgkI8b-_5ZsaEAIQAA"; // <GPGSID>
        public const string achievement_master_bird = "CgkI8b-_5ZsaEAIQAQ"; // <GPGSID>
        public const string achievement_pro_bird = "CgkI8b-_5ZsaEAIQAg"; // <GPGSID>
        public const string achievement_master_dropper = "CgkI8b-_5ZsaEAIQCw"; // <GPGSID>
        public const string achievement_all_star_dropper = "CgkI8b-_5ZsaEAIQDg"; // <GPGSID>
        public const string achievement_master_collecter = "CgkI8b-_5ZsaEAIQBg"; // <GPGSID>
        public const string achievement_all_star_reviver = "CgkI8b-_5ZsaEAIQEw"; // <GPGSID>
        public const string achievement_rookie_collecter = "CgkI8b-_5ZsaEAIQBQ"; // <GPGSID>
        public const string achievement_master_reviver = "CgkI8b-_5ZsaEAIQEA"; // <GPGSID>
        public const string achievement_share = "CgkI8b-_5ZsaEAIQFg"; // <GPGSID>
        public const string achievement_all_star_collecter = "CgkI8b-_5ZsaEAIQCQ"; // <GPGSID>
        public const string achievement_ultimate_reviver = "CgkI8b-_5ZsaEAIQEg"; // <GPGSID>
        public const string achievement_rookie_dropper = "CgkI8b-_5ZsaEAIQCg"; // <GPGSID>
        public const string achievement_rookie_reviver = "CgkI8b-_5ZsaEAIQDw"; // <GPGSID>

}

